### ISSUE TITLE
type: schedule broken I believe

### ISSUE THREAD

**Issue by freqyfreqy** [YukiGasai/obsidian-google-calendar#106]
Hi I believe 'type: schedule' is broken. would you mind taking a look at my screenshot?
I've shown a page with LP/Reading mode and source mode and the working schedule view created by the command "Open gCal schedule view".
<img width="2066" alt="Screenshot 2023-04-04 at 07 15 07" src="https://user-images.githubusercontent.com/96843562/229821246-33d90d3a-941c-47ae-87b7-9721225c5d63.png">

**Comment by YukiGasai** [comment]
Hi @freqyfreqy,
thank you for showing that the view works at all. 
I want to make clear that the web view is not related to all the other views, because it just embeds the Google calendar page no OAuth required, so please always test another view if you are loged in.

In your case, please test if the code block works without the `exclude` parameter.
This should be an array of string like this

`exclude: ['CalendarA', 'CalendarB', 'ColorA', 'ColorB']`
