### ISSUE TITLE
Change the start Date of weekView

### ISSUE THREAD

**Issue by NNoah18** [YukiGasai/obsidian-google-calendar#109]
When using the codeblock to add a week view to a page, I want to be able to manually set the start date. I noticed that by manually changing the date it will change the start date to equal the date, however I only want to change the start date of the week.

I would also like to be able to change the start date of the month view in codeblock.

**Comment by YukiGasai** [comment]
Hi,
please make sure you habe installed the latest version.
For the week view you can set the `dayOffset: <number>` option.

I will try to add this option for the month view as well.

**Comment by NoahSTEMStuff** [comment]
Thanks for the speedy reply!
I am trying to make a template, so I do not actually know the number of offsets until after I create the file. Basically I want to have a dedicated page for every week, and embed a view of that week to the file. 
So for example, say I want to preview what my schedule will look like 2 weeks from now, I could manually enter in the offset, but that defeats the purpose of the template. Also if I try and view it the next day or next week I would have to adjust the offset. 

So I was wondering if it would be easy to add a startDate Parameter, so that I could use it like this in a template?
![image](https://user-images.githubusercontent.com/115769149/230837010-5aba745c-b933-4bc6-b3c3-1a74d20e0482.png)

So once I generate the weekly notes for a week, for example week of may 7th, it looks like this:
![image](https://user-images.githubusercontent.com/115769149/230838273-17f5bc72-6de9-455f-b857-454896b3fef8.png)
However, the parameter startDate currently has no effect so it still only displays the current week, which is the one starting on 04/09.

Otherwise I could just use the date parameter instead, however, then the today button would not be linked to the correct day.

**Comment by NNoah18** [comment]
Thanks for the speedy reply!
I am trying to make a template, so I do not actually know the number of offsets until after I create the file. Basically I want to have a dedicated page for every week, and embed a view of that week to the file.
So for example, say I want to preview what my schedule will look like 2 weeks from now, I could manually enter in the offset, but that defeats the purpose of the template. Also if I try and view it the next day or next week I would have to adjust the offset.

So I was wondering if it would be easy to add a startDate Parameter, so that I could use it like this in a template?
![image](https://user-images.githubusercontent.com/4433959/230838956-58d716b2-db02-4443-87af-450e374bcdcb.png)


So once I generate the weekly notes for a week, for example week of may 7th, it looks like this:
![image](https://user-images.githubusercontent.com/4433959/230839021-fee8868c-cf64-49d1-9f92-7011ae1a9482.png)

However, the parameter startDate currently has no effect so it still only displays the current week, which is the one starting on 04/09.

Otherwise I could just use the date parameter instead, however, then the today button would not be linked to the correct day.

**Comment by YukiGasai** [comment]
Have you tried using the `date` option?

**Comment by YukiGasai** [comment]
Closed due to inactivity.
