### ISSUE TITLE
I keep needing to logout and login frequently for the plugin to work.

### ISSUE THREAD

**Issue by machado-t** [YukiGasai/obsidian-google-calendar#149]
Without any notice, the plugin frequently (~twice a week) stops working. I figured a way to make it work again: I logout and login again in the settings, which is a pain. Any idea why this is happening? Thanks

**Comment by hx2A** [comment]
I'm having the same problem. Have we done the setup incorrectly? What can we do to help you debug this?

**Comment by YukiGasai** [comment]
Hi, I am currently reworking the OAuth process as part of my bachelor thesis, that should address this issue. But it will take some more time to finish everything. You can test the updated process from the Branch ba-auth-improvments if you like.

**Comment by hx2A** [comment]
> Hi, I am currently reworking the OAuth process as part of my bachelor thesis, that should address this issue. But it will take some more time to finish everything. You can test the updated process from the Branch ba-auth-improvments if you like.

Excellent, thank you very much for your reply. I can certainly be patient and will wait for you to make that change to this most useful Obsidian plugin.

**Comment by mathisgauthey** [comment]
Hey there, same issue here, I'll be waiting as well!

**Comment by YukiGasai** [comment]
I checked the new version of the OAuth process and think that the same issue could occur there.
My guess is, that the OAuth Refresh Token will get invalid after seven days because the project we all created is running in test mode. [Google Docu](https://developers.google.com/identity/protocols/oauth2)
![image](https://github.com/YukiGasai/obsidian-google-calendar/assets/38146192/a69a070f-7c9c-43a2-a9e6-5b9b0b276bea)

A possible solution could be to switch from test to production inside the [Google Cloud Console](https://console.cloud.google.com/apis/credentials/consent).
![image](https://github.com/YukiGasai/obsidian-google-calendar/assets/38146192/99408d58-bf11-42bc-877d-1b9a30a1bf0c)
Google will ask for a validation, but as long as everyone is using their own client after [google guidelines](https://support.google.com/cloud/answer/9110914?sjid=2051518793422829407-EU#exceptions-ver-reqts&zippy=%2Cexceptions-to-verification-requirements), no verification is needed. The drawback is an extra screen during the login process that will warn the user that the client is not validated by google.
![image](https://github.com/YukiGasai/obsidian-google-calendar/assets/38146192/bf548cf3-cb9e-4e65-81bd-2be0119cd0d1)


I will test this myself, and it would be nice if someone else could test this idea.

**Comment by mathisgauthey** [comment]
> I checked the new version of the OAuth process and think that the same issue could occur there. My guess is, that the OAuth Refresh Token will get invalid after seven days because the project we all created is running in test mode. [Google Docu](https://developers.google.com/identity/protocols/oauth2) ![image](https://user-images.githubusercontent.com/38146192/258886675-a69a070f-7c9c-43a2-a9e6-5b9b0b276bea.png)
> 
> A possible solution could be to switch from test to production inside the [Google Cloud Console](https://console.cloud.google.com/apis/credentials/consent). ![image](https://user-images.githubusercontent.com/38146192/258887399-99408d58-bf11-42bc-877d-1b9a30a1bf0c.png) Google will ask for a validation, but as long as everyone is using their own client after [google guidelines](https://support.google.com/cloud/answer/9110914?sjid=2051518793422829407-EU#exceptions-ver-reqts&zippy=%2Cexceptions-to-verification-requirements), no verification is needed. The drawback is an extra screen during the login process that will warn the user that the client is not validated by google. ![image](https://user-images.githubusercontent.com/38146192/258888824-bf548cf3-cb9e-4e65-81bd-2be0119cd0d1.png)
> 
> I will test this myself, and it would be nice if someone else could test this idea.

Hi there, I wanted to give it a try but it appears that publishing the app would make it visible and usable by anyone with a google account, wheareas it was only accessible to people we added on the user step of your guide before. If you have some informations about that before I test it on my end as well, I'd be glad !

**Comment by YukiGasai** [comment]
Hi, it is correct that if you publish the app everyone with a Google account could use it, but they need to also have your Client ID and Client Secret, that you should not share.

**Comment by mathisgauthey** [comment]
> Hi, it is true that if you publish the app, anyone with a Google account can use it, but they also need to have your Client ID and Client secret, which you should not share.

Fine by me then, I'll do the changes required and keep you updated ✌️

**Comment by adamhl8** [comment]
@YukiGasai I published my app over a week ago and haven't been logged out since, so it seems like this definitely solves the issue. Maybe it would be worth referencing this issue in the readme?

**Comment by Triquetra** [comment]
I noticed instructions on [this similar plugin](https://github.com/dexin-qi/obsidian-sync-calendar) to obtain an OA Client credentials file. Might that be a better solution?

**Comment by mathisgauthey** [comment]
@YukiGasai same here for me, the changes worked, I don't have to reconnect every week now.

**Comment by halldk** [comment]
Thanks! I was wondering about this.
