### ISSUE TITLE
Display data from obsidian-google-tasks

### ISSUE THREAD

**Issue by pm64** [YukiGasai/obsidian-google-calendar#196]
The ability to display events and tasks simultaneously on the native calendar views would be huge.

I'm not familiar enough with the Obsidian API to know if plugins can easily share data. But if so, consider a new option for this plugin such as "Show tasks from obsidian-google-tasks on gCal calendars".

In my case, I use "Open gCal month view", and would like to see dots for both events and tasks (with different dot color) in this view.

**Comment by YukiGasai** [comment]
Hi,
I know that the Google tasks plugin didn't get any attention for the last months. That's because I am no longer using it for task management and focusing my attention on other stuff. I am waiting for the resolution of this [google issue](https://issuetracker.google.com/issues/128979662) and would then try to add some google task features to the Google Calendar Plugin directly.
Sharing data between plugins is possible, but would require nearly the same amount of work as just implementing it directly.

**Comment by pm64** [comment]
Ouch, I'm familiar with that issue and personally believe it's unlikely to ever be resolved, which is a pity.

But worth noting that Obsidian doesn't have native support for task due times, either.
