### ISSUE TITLE
Feature: option for Month View to expose Calendar plugin-like functionality

### ISSUE THREAD

**Issue by pm64** [YukiGasai/obsidian-google-calendar#26]
The main use case for the Calendar plugin is quick navigation between daily notes. It seems to make sense for obsidian-google-calendar to give the user an option for Month View to provide similar functionality -- basically adding the ability to create and open daily notes.

Currently, when a day in Month View is selected, a list of calendar events on that day is displayed. An item could be added to that list, for example, labeled "Add new daily note for 11/7/2022" or "Edit daily note for 11/7/2022".

The main motivation for this is the popularity of the Calendar plugin. It's likely that a large percentage of obsidian-google-calendar users are also Calendar plugin users, and will thus spend time switching between plugin panes and navigating multiple calendars.

**Comment by YukiGasai** [comment]
Hi,
I understand the point you are making here.
I will have to think a little about this, because this has not really something to do with the google calendar and would go a little against the purpose of this plugin. 
On the other hand, it sounds really useful.

**Comment by YukiGasai** [comment]
@pm64 I decided to add your idea to the plugin, but because it's not the main purpose, it's locked behind a setting. Activate the `Show daily notes` option to use it.

If there are more spots where the daily notes should appear, please say so.

Currently, you can see your daily notes in the month view highlighted by the dot with the custom color.
![grafik](https://user-images.githubusercontent.com/38146192/202030926-50241b1c-0a3a-4264-9e5a-accd3f7e0ca5.png)
 And you can create/open them from the event select.
![grafik](https://user-images.githubusercontent.com/38146192/202030892-e037452f-0409-4768-a486-dc5f6903509a.png)

**Comment by pm64** [comment]
Beautifully done, @YukiGasai -- huge thanks on behalf of the community for this important enhancement.
