### ISSUE TITLE
New command: Create Google Calendar Event from note frontmatter

### ISSUE THREAD

**Issue by DanielMuresan2** [YukiGasai/obsidian-google-calendar#30]
Can you please create this? I'd greatly appreciate it. Thanks!

**Comment by YukiGasai** [comment]
Hi @DanielMuresan2,
thanks for this suggestion. I added the command and would like to know your opinion.

You can fully customize the event you generate by using the YAML to set the data of the event
For all the possible options, take a look [here](https://developers.google.com/calendar/api/v3/reference/events).

To make it more usable:

- not setting a summary or title will default to the note's file name
- not setting any start or end date will default to today
- you can directly set start, end or startTime, endTime instead of creating a start or end object
- setting the start date but not the end date will default to the start date

Maybe you have more ideas of making this feature user-friendly.

Example
```
---
summary: Woow
start:
 date: 12/07/2022
end:
 date: 12/09/2022
---
```

**Comment by DanielMuresan2** [comment]
Yuki, you are just amazing. I tested it and it works like a charm. For me personally, this feature along with Templater unchains the ultimate to-do list framework. You may consider posting an update on r/Obsidian on Reddit regarding this change, because it is BIG.

**Comment by CovetingEpiphany2152** [comment]
This looks awesome! Is there any way to make it work with custom yaml fields (user specify which fields for title, start, end, etc). Also to work with dataview inline fields?

**Comment by CovetingEpiphany2152** [comment]
I haven't had time to test your changes out. Will try to find time during the weekend. Looks like you even have a commit up for dataview inline fields. Mindblown by your speed @YukiGasai !

**Comment by CovetingEpiphany2152** [comment]
Okay, I did a quick test but can't get it to work. I bet I'm missing something obvious.

I'm using the frontmatter you suggested to start simple

```
---
summary: Woow
start:
 date: 12/07/2022
end:
 date: 12/09/2022
---
```

But I got this error:

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'parent')
    at eval (plugin:google-calendar:75:88312)
    at Generator.next (<anonymous>)
    at eval (plugin:google-calendar:6:1338)
    at new Promise (<anonymous>)
    at U (plugin:google-calendar:6:1158)
    at hh (plugin:google-calendar:75:88259)
    at eval (plugin:google-calendar:94:6603)
```

Tested on:
Obsidian version: 1.0.3
Plugin version: 1.7.1
OS: Windows 11 22621.819

Btw, how do we specify which calendar the event should be created in?

**Comment by CovetingEpiphany2152** [comment]
Works like magic! Perhaps a notice that no default calendar is set could be helpful if the user were to try it without setting one?
For the topic of event creation, I think there are two more things that could be done:

- recurring events (yikes painful!)
- event description

I have suggestions on how I think the feature would make sense (but of course, this is just my use-case).

## Recurring Events

The current UI to create recurring events is based on fixed-intervals. It is unable to support things like "every month on second friday" or "every year on the third last wednesday", etc. I think it would make more sense that for the purpose of event from note, we support the [RFC5545](https://www.rfc-editor.org/rfc/rfc5545) which I believe is what is used by the Google Calendar API.

However, typing out RFC5545 recurrence rule is incredibly cumbersome. So my suggestion is that you use something like the  [Rrule node module](https://github.com/jakubroztocil/rrule) which is also used by Obsidian Task plugin. You can let the user put in a string like "every month on second friday", throw the [start date, user text, end date] to `RRule.fromText()`, and convert it into RFC5545 format using `RRule.toString()`. Viola, you can now pass this to Google API.

The work for this might be worth another issue though, it also paves the way to better recurrence support for the UI too.

## Event Description

Currently, the event created with command creates an event with no description. I think we can choose one of the following to populate the description with.

- let the user specify a string, which is a header. all content from that header onwards will be copied for the event description
- let the user specify an array of strings, each for a header. the headers and contents nested within those headers will be copied for the event description

---

Again, these are just my suggestions. Amazing job so far. Thank you so much, for your incredible work!

**Comment by CovetingEpiphany2152** [comment]
I think I have found a small bug,

The following spawns an all-day event that is on 12/14, all good.
```
---
summary: hm
start:
 date: 12/14/2022
end:
 date: 12/14/2022
calendar: [to-do]
---
```

However, if you add one onto the end date, you still spawn an event that is all-day on 12/14, instead of spanning from 12/14 to 12/15. This is inconsistent with the Google Calendar application (it would spawn a 2-day event instead).

```
---
summary: hm
start:
 date: 12/14/2022
end:
 date: 12/15/2022
calendar: [to-do]
---
```

And this spawns a 2 day event instead of a 3-day event. So it looks like an off-by-one error to me.

```
---
summary: hm
start:
 date: 12/14/2022
end:
 date: 12/16/2022
calendar: [to-do]
---
```

**Comment by YukiGasai** [comment]
Thank you for your feedback and testing.
I will work on the bug for now, but have already created 2 issues for your suggestions. Let's continue the discussion there.
