### ISSUE TITLE
Unable to use the plugin on mobile

### ISSUE THREAD

**Issue by preslavnpetrov** [YukiGasai/obsidian-google-calendar#57]
Not sure how to extract logs for what exactly is going wrong, but when I try to enable the plugin, a notification pops up saying it failed to load, and it disables the plugin. The same doesn't happen on Desktop

**Comment by YukiGasai** [comment]
Hi @preslavnpetrov,
thank you for bringing up this issue.
Mobile support is very annoying because it breaks with the most common things. In this case, I added support for desktop notifications using electron. Electron is not used on the mobile app… 

Please try to install the latest version. If the plugin is working as expected, you can close this issue.

**Comment by preslavnpetrov** [comment]
You're a star. New version fixed it.
